### ISSUE TITLE
Add MySQL JDBC Driver

### ISSUE THREAD

**Issue by JKNetwork** [cptactionhank/docker-atlassian-jira-service-desk#2]
It would be nice if you can add the JDBC MySQL driver to the image.

**Comment by cptactionhank** [comment]
It already is added

```
curl -Ls "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.38.tar.gz" | tar -xz --directory "${JIRA_INSTALL}/lib" --strip-components=1 --no-same-owner "mysql-connector-java-5.1.38/mysql-connector-java-5.1.38-bin.jar"
```

and there is acceptance tests using MySQL as an external database. Can you elaborate on what you are experiencing to conclude the MySQL is not available?

**Comment by cptactionhank** [comment]
Closed due to inactivity and it was never and issue to begin with
