### ISSUE TITLE
SSL issue in swarm mode

### ISSUE THREAD

**Issue by davidwmartines** [cptactionhank/docker-atlassian-jira-service-desk#7]
I am running this as a service in docker swarm, using docker-flow-proxy to route based on host name.  I publish the Jira service on port 8080 and route requests based on 'myhostname.com' on 443 to it, using docker-flow-proxy serviceDomain labels.  SSL cert is added as a docker secret, and is picked up fine.  It all mostly works - the Jira web app runs and I've gone through the database configuration successfully, but I am getting occasional errors and warnings in Jira UI like the following:

> The Tomcat server.xml has an incorrect configuration:  
> **scheme** should be https
> **proxyName** should be 'myhostname.com'
> **proxyPort** should be '443'

> Dashboard Diagnostics: Mismatched URL Scheme
> JIRA is reporting that it is using the URL scheme 'http', which does not match the scheme used to run these diagnostics, 'https'. This is known to cause JIRA to construct URLs using an incorrect hostname, which will result in errors in the dashboard, among other issues.
> 
> The most common cause of this is the use of a reverse-proxy HTTP(S) server (often Apache or IIS) in front of the application server running JIRA. While this configuration is supported, some additional setup might be necessary in order to ensure that JIRA detects the correct scheme.

` com.atlassian.gadgets.dashboard.internal.diagnostics.UrlSchemeMismatchException: Detected URL scheme, 'http', does not match expected scheme 'https'
	at com.atlassian.gadgets.dashboard.internal.diagnostics.Diagnostics.checkExpectedScheme(Diagnostics.java:52)`

I've looked all throughout the container and can't find tomcat server.xml to edit.
I think this issues is similar to what they describe here: https://confluence.atlassian.com/adminjiraserver073/integrating-jira-with-apache-using-ssl-861253896.html

Please help in how to configure properly.

**Comment by davidwmartines** [comment]
I found the file to edit: /opt/atlassian/jira/conf/server.xml.  and the required changes from https://blog.valkyrnstudios.net/tech/jira-and-haproxy-with-ssl-offloading/

However, is there a way I can mount this /opt/atlassian/jira externally, so the file can be edited and persisted across container instances?

**Comment by cptactionhank** [comment]
You can mount a file externally by mounting the file and I highly encourage all to learn how to use the tools to run the image, being both Docker and JIRA:

* https://docs.docker.com/engine/admin/volumes/bind-mounts/
* https://confluence.atlassian.com/kb/proxying-atlassian-server-applications-with-apache-http-server-mod_proxy_http-806032611.html

The following environment variables can help configure this when starting the image, just craft your command accordingly

Environment Variable | Description
-- | --
X_PROXY_NAME | Sets the Tomcat Connectors ProxyName attribute
X_PROXY_PORT | Sets the Tomcat Connectors ProxyPort attribute
X_PROXY_SCHEME | If set to https the Tomcat Connectors secure=true and redirectPort equal to X_PROXY_PORT
X_PATH | Sets the Tomcat connectors path attribute

**Comment by davidwmartines** [comment]
Thank you.  Using the environment variables seems to have solved the issue.
